apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssmush.fullname" . }}
  namespace: {{ include "ssmush.fullname" . }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}